# GitHub Sponsors
github: tamylaa

# Open Collective
open_collective: clodo-framework

# Ko-fi
ko_fi: clodoframework

# Patreon
patreon: clodo

# Custom sponsorship URLs
custom: ["https://clodo.dev/enterprise", "https://clodo.dev/sponsor"]